Include default configuration for Contao managed edition
1up-lab/contao-sentry-bundle pull request #12
Opened 2024-04-29 15:10 UTC by aschempp

This PR adds some default configurations if the bundle is included in a Contao Managed Edition. Because most times, the configuration will be identical and repetitive.

I also added an event listener to filter previous exceptions. In my case, I had Twig components throwing an `AccessDeniedException` (which correctly triggers the firewall), which are logged as `RuntimeError` even though the previous exception was one to be filtered.

The namespace also changed from `Oneup\Contao\SentryBundle` to `Oneup\ContaoSentryBundle` which I think would be more correct in terms of Composer packages.

@fritzmg @richardhj any opinions on this?

**TODO**:
 - [ ] Update README

2024-04-29 15:18 UTC, bytehead commented
/cc @Shadow-Devil

2024-04-29 15:25 UTC, fritzmg commented on config/skeleton.yaml
> +    '%env(SENTRY_ENV)%': '%kernel.environment%'
```suggestion
    env(SENTRY_DSN): ''
    env(SENTRY_ENV): '%kernel.environment%'
```

2024-04-29 15:26 UTC, fritzmg commented
I also have

```
Symfony\Component\Security\Core\Exception\AuthenticationException
```

in my `ignore_exceptions` list.

2024-04-29 15:30 UTC, fritzmg reviewed
I usually only set `sentry.dsn` and `sentry.options.ignore_exceptions` in my projects. Why do you also set `sentry.register_error_listener`, `sentry.register_error_handler` and `monolog.handlers.sentry`? i.e. what's the purpose/advantage.

2024-04-29 15:31 UTC, Shadow-Devil commented
Would this be a major version release since all PHP, Contao and Sentry minimum versions were increased?

2024-04-29 15:32 UTC, bytehead commented
> Would this be a major version release since all PHP, Contao and Sentry minimum versions were increased?

Yes.

2024-04-29 15:34 UTC, richardhj commented on src/Twig/ContaoSentryTwigRuntime.php
> +            return (string) $dsn;
I think there must be a reason why I did not use `getDsn()` before. But if it works :-)

2024-04-29 19:19 UTC, aschempp commented on src/Twig/ContaoSentryTwigRuntime.php
> +            return (string) $dsn;
I thought about that too but couldn't find any 😅

2024-04-29 19:20 UTC, aschempp commented
> I usually only set `sentry.dsn` and `sentry.options.ignore_exceptions` in my projects. Why do you also set `sentry.register_error_listener`, `sentry.register_error_handler` and `monolog.handlers.sentry`? i.e. what's the purpose/advantage.

I was wondering that as well, but that's what the official docs say: https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration

> If you have monolog …

I know that we do often get error messages twice in our projects (with the same setup you have). I can only assume that's because Monolog integration is logged to sentry as well as the error handler 🤔

2024-04-29 19:35 UTC, fritzmg commented
Hm, I never get error messages twice - I only get multiple sentry entries when there are previous exceptions, which your PR fixes. imho the default config without configuring monolog is enough.

2024-04-30 05:59 UTC, aschempp commented
🤔 https://github.com/symfony/symfony/issues/36472#issuecomment-616210651

I think the reason is that you can only have one error handler in PHP, and if you already have Symfony/Monolog handling the errors, you don't want Sentry to override or interefer with that.

https://github.com/symfony/symfony/issues/36472#issuecomment-616774302

2024-04-30 08:51 UTC, fritzmg commented
Ah, I see 👍

2024-04-30 08:52 UTC, fritzmg approved these changes

2024-04-30 12:16 UTC, aschempp commented
Another big advantage I just noticed: this now also logs **all other monolog errors** to Sentry! In my case the CSP violation logged by Contao was added to Sentry 😎

2024-04-30 12:18 UTC, fritzmg commented
Which is something that should be ignored though imho 😁 CSP reports can be quite spammy.

2024-05-03 07:55 UTC, aschempp commented
> Which is something that should be ignored though imho 😁 CSP reports can be quite spammy (as anyone can send anything to the controller).

well yeah… but Sentry also has specific CSP monitoring, which would make more sense than this. But not really related to this PR 😆

2024-05-03 07:57 UTC, aschempp commented
@bytehead are you ok with the namespace change or was that "group" intentional? In our bundle, we would actually use `Oneup\SentryBundle` because the `contao` part is fictional to me, to show the package is built for Contao. But there's never gonna be a `Terminal42\DcawizardBundle` that is _not_ for Contao, so no point in adding Contao to the namespace.

2024-05-03 08:01 UTC, fritzmg commented
Personally I would definitely call it `Oneup\ContaoSentryBundle` as there already exists a `Sentry\SentryBundle` - which the `Oneup\ContaoSentryBundle` loads for the Contao Managed Edition. Calling it `Oneup\SentryBundle` would make it look like a fork of `Sentry\SentryBundle` imho - which it is not.

2024-05-03 08:34 UTC, bytehead commented
I would optin for `Oneup\ContaoSentryBundle` 👍

2024-05-15 09:01 UTC, aschempp commented
I have now used this on several systems in production, and it seems to work fine 🙃

2024-05-21 10:38 UTC, bytehead commented
Back from holidays, I'll have a look this week!

2024-05-22 11:27 UTC, bytehead requested changes
Looks good to me apart from the service naming (best practices).

2024-05-22 11:27 UTC, bytehead commented on config/services.yaml
> +    Oneup\ContaoSentryBundle\Twig\ContaoSentryTwigExtension:
As of current best practices we should not use FQCN as service ids.
```suggestion
    oneup_contao_sentry.twig.extension:
        class: Oneup\ContaoSentryBundle\Twig\ContaoSentryTwigExtension
```

2024-05-22 11:27 UTC, bytehead commented on config/services.yaml
> +    Oneup\ContaoSentryBundle\Twig\ContaoSentryTwigRuntime:
As of current best practices we should not use FQCN as service ids.
```suggestion
    oneup_contao_sentry.twig.runtime:
        class: Oneup\ContaoSentryBundle\Twig\ContaoSentryTwigRuntime
```

2024-05-22 11:27 UTC, bytehead commented on config/services.yaml
> +    Oneup\ContaoSentryBundle\Integration\IgnorePreviousExceptionsIntegration: ~
As of current best practices we should not use FQCN as service ids.
```suggestion
    oneup_contao_sentry.integration.ignore_previous_exceptions:
        class: Oneup\ContaoSentryBundle\Integration\IgnorePreviousExceptionsIntegration
```

2024-05-22 11:27 UTC, bytehead commented on config/skeleton.yaml
> +        before_send: Oneup\ContaoSentryBundle\Integration\IgnorePreviousExceptionsIntegration
```suggestion
        before_send: oneup_contao_sentry.integration.ignore_previous_exceptions
```

2024-05-23 11:40 UTC, bytehead approved these changes
❤️

2024-05-23 11:50 UTC, merged

2024-05-23 11:51 UTC, bytehead commented
Thank you @aschempp & @fritzmg!